tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SANDBOX_ROLE
      database: SANDBOX_DB
      schema: RS_DEV
      warehouse: SANDBOX_WH
      threads: 4
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SANDBOX_ROLE
      database: SANDBOX_DB
      schema: RS_PROD
      warehouse: SANDBOX_WH
      threads: 4
