bcbspoc:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: nu51811
      user: sriramk
      role: accountadmin
      database: BCBS_DBT_DB
      schema: dev
      warehouse: COMPUTE_WH
      threads: 8
    prod:
      type: snowflake
      account: nu51811
      user: sriramk
      role: accountadmin
      database: BCBS_DBT_DB
      schema: prod
      warehouse: COMPUTE_WH
      threads: 8
